### ISSUE TITLE
Update FreshySites logo

### ISSUE THREAD

**Issue by Garconis** [FreshyMichael/freshysites-support-beacon#6]
Logo in the widget should be updated to our newest version... as well as the FS logo in the chat toggle.

**Comment by FreshyMichael** [comment]
> Logo in the widget should be updated to our newest version... as well as the FS logo in the chat toggle.

Logo updates will be included in the next plugin update, currently scheduled for later this month. Just a note, we're moving this from my GitHub account to the support account in the next update as well. Future issues can be reported here: https://github.com/FreshySitesSupport/freshysites-support-beacon/issues
